var htmlConfig = {
    "bookConfig": "v010001102ae4ZgvJWq2LVpwMYouHanzCTh7GfouDdj5IRt7Lbg2ISpvCXuzDUtxKfj5CZivHTtvBYq3Ieu5Cfq9Ofp8EUn2PfhuISo3BVmwBSlxEVgxJZjwDQp0PauuFQg8MWn8AasyFXt0NSu3Oel5PTgxAXo0Des3NSt3IYsvBWg5Lcr8ATt6ObkwAQh5CZl4OcnxITt2Ocj9EdrzJTvuHbp3OZozOSt2NXryFQo0NUp7DQo1AStxDfgxPTivEcg1KXtzFVgzIWu4Gbj7MZg0Bal5AVqvAWjxBbh0OWsyJRsuFToxPUs6LVm4CYr9EXhzHVv2Hfi7ASk2Gbj1Dfv2GUpxLWj5IWl6OYq8Oai2EUn3ARhvAWm8DaovOfm3GeuvBZg8MVv8Cfu6EYh5DdiyOcn3KevzLWv3Gao0NZixBbmxOQg7LQm7MVv7IRp8FUr4Aeg5OekvLbhzCet4EejzMckwOXlwKRp8IVu1ARi5Bbp3OVtyAaj2Dbq5LQo5NZg9ATl7HXk0MTl9BQo2NfpzDVpxGWo9Ofr1Obr3DZtzKcm2PXi8CQi5Jbv6OUl1Aat7AUoyDckyHcr9Abr5NRo9IXg8HZl9JfjxAav2HUv8LTlwEVv7FTpyCWp9FQrvPbn6MRm6Kbs5BVg6KZuzKZo0EYgwPQu3JRl3IYp2LZs4Ack1KdkuPXjwHTp2AWj7CVqwEckyOcn5Fep5CUg5KVj4ITp1IYs1FcozNVsvEXr4Les7NQt9JSu6PRg2MSl4GXhvIVt6LQnwLcq9ESmwNRgyFcszHel0LTh4LWu7DTn0NWvuGWt7Afh6Gck8NVu6EXi8FSk9FSr8IRl4OUp2OYl6ERk5Hav8KVvvIQgzIXj0IerxEapyLRp9CUmxIdq9MYmuJct6LUj4MVmyBVvvGfu0BXmzEfi8MXq5JVkvIVt8Fdk4PUu0Bei1MTk4MSpyEVs2PTs3NSr2MZrwBZj1BXmyJdrwEXg5DUvyIXquEXj3JTg8NXt5Afg4HYg8MRr4BViyDdg4ETsxCRqxBaj7IerwJYnxOamvIYl0EYtuGbguIVh5IZgwGYj3CVkzLel8LXh2PWm2PRr9Jcs2Ofn1CZlwNXm1LQi6LakyIUouDfo0LVv7FcpuMVn9AQr9KWguHSt9AcgwAbi0FVl2ARq3LemyGWl4HTnzFck9BTh1GWlwDci6PVl4LbpvKYmwDQn9LdpvETqwKWhxMes0Aau6Jar4EUuuKXm2NfmzNYpyNXk5Kbn7Ccm9Fdj1DRg1HQq8HavuGVlxHSj5ATv0LTq8OWjyLck1MYuuJZqyEWl4Gds0GUi1CXt7MRt1DYl7BRs6AVk1OQhyLYn3Kcj8PQr4Nag2CYv5IWj7FQr7DRl5GTsuCVi2OcuuGWuuKXv8MWi6AUu8FSnyNfpxPck6CTj5AQj4Fes8EUv8FRkyLZr2Cbo9CSt7IQo4FbsvIZm3NZm9FSj9Hfi0PeovMUryDcgyGUt6NauxKVu9Hbt8BYi3KTryJdjyDeo1LWqzDQjyPVg3FUg7MQh4Fal9MbkuGVk0IWsuHWp4Bau4Kfp4ITr1OQgxEWv0Deo4Kft7MSqvLSuuBYs9CWkzJWt4GTq0OWl5IZv0CZuvBQnvDdgvAbp8KQg1Lci4AQrvOaqxLQm8Nep2HXs4LchvAXlwAUh4DUn5ISryCUmuPcr2AQi7Bbg3PZk3AVi2PWt1EVqvGYlwIQtzDapzDSh2Eel2ARj6MUsyNYkvIboxNan6Eev3HWozJVm3KRjwPWuvIZhvKch0CRv7ORs8LclwLQuxISm7KfgvDduxHWu2PWn4MViyPcg2Dfo3CSj6PXp8PThuNVm3MWs7PSq3Ldn8BVruPVj3NVl2LbgzJat3Efj9DYq3Ccp9FXr4Ibo1JQp4PWnyGSj5Mfi9EdluHXhvIdi6FWj6DSj7HTs8IdlyBWixGQu0LZh0MdnxKYvyIRh8JRp9Fbh1CUjvNWq6Abn0EZvxNbu3PZoyASn0GSpxNTnyJYl2AVg6EQs5Lcl7GagzFfv0Aeg4GYi3DYs5BQp9Nas9BXgwLSswHdjvFfvzHQiwOTqwFTp9PVg5Idt9KVmxHVn3HRp4JahyGen3HQouIZlyAfi0CZq3Hem3Ibr8Jfi7Ceu9DUo2OaruIXk7EUiyFck8Gct1KRl4ETi4AXl8IUqyKVjuMel2GWm1BQo4BXu4JXqxKWp1Lbj7PVtuEYmyIag4JYpwHaoxDUt4Mai3Lfk9Hdp9GSg7ARj6ISi3Afs7NdkuFakyKdgzFYgwPdr0OWtuAUjwBdk4GQp6Kfl7FdixLbhvJYpuLZgwObg0Eei6EUk9OWizJVivOSo3OUk9DWv2MUsxIZsuMTm8PfiyEcp6FTu8Nbn7CVo6KZv6Gfr0OSv0Kcu6LevwKcs9ARq4MdvvHTn9Hci9Fdh5GSk3CduuJfu5ERsvLfnzFQguKTtzKXj7DchwEfg3BYpuEdh3Mfq1MWvzFXv1OQs4Ian4EZgwGXk5PRi2Lat5MUpxEbl3PYs0Bai2FTuxPdh7BYmxIdt8HSgzMfmzFcu5Abp7AevyITkyLbk7PWjzCTg4Acg8PXk9MbqxPcmvBWkvJXlyBTpzCci6FRh5EenwGRu5IXr3Ecq4BSl9DVvwBes7ESuyAYu8HZh7MfmxGfm2DUqxMQi9GQt2KejxKUh9ARp1BWq5HRl6AfkwMdp7LXt1Fbn0GYn7OQv3IbrxNTm7Edj6GbluFai8OQjxJTozJRr1CZt0BXg3IUo5PYm5NctvGZkwOau2MdswHXoxMWi3OXkwPUn8EZmvHRm7CZmuFUt5NXg3GTl4Adt9Kfl4Abu2Edn0CUh1OUt3IUv6EQm3DVpuDTu6FXt4FZk3Caq3FVs0Iev3ETmxKfo6NaruEeg4FasyBYr5GQv2Ach5KZk8NelxDVg5MTjyGeguFfo1Pdk2HdjyAequAYqzIds9FXkzNRs7AWmxHbnxKZluGYt3Jes7CRquObo4PSv3Iat9Lev0Lfk7AVh3LYn4KRtyOWtzIdkzFXvuARr8BVh6NVq5EWl3Iei5JYn3MYsyCcq1Dam3LYp5IeuzBdiuEZg2Kbn8Edv9BfiyDXjzLXt9CZg4DWryIQh2ASv3Bft2Acq6Ael2MYp9Pfv8Kbm6CQpyDTg3PVn0FYi1CVnvAQr0CVv5EXr9PWh4KRiuBduxCQjzKdj5Ibv0DQu4GStvPWlyIVk2KRlvIdr9HWg6DYj8FaryOeo6Ccu9IYpvIWj3Gcs8Kdp2DWnxORq2BXp7ESq5MSl3IckxNbu9Ecq9Obs1HZpwPfu8OeoxNWtxFTu8Mcp3KSr3IbmwMRtuNXm7Las2OSp7GQt8FWvuEVm2KbgyBUgwBfuvMYu7NTlvBRryDRi3HSj2BRrxISs4OQn0NVpvKXhxFWo4GXtxCXtxObq6DVm3JRmuDRg2ARj0NUoxJcoyETp6MRr3BQj3DSozKTgzCfpwNct7Nfn6IYk5AQg9AZvyFai3BRs7MTl7JRovPTjwMRuuBVi2FQs0FRgzJbq4IftvCfgxNcu8EVr7LZo7BWhuCZjvBao1OSr2MRi0MbryNdiwARgxLeiwJWs9AaiwFet8NSv4CUo9ITt3McivJZr9Edk5GZo7BVo1Hcn8CZt8CQs0GZozJQq1OXv8GVoyLUlxOVg7AQtwJUk6GYl1Eap2AQh3DWiwIRozLen8FQi4FZl6EfkxNYn7GRrvLTh3Hbo2FZg1Jct4PbpxFZh3FUj1BVrwLat1JYhzOWozKdj5IWryKeoyLcgzCbs5BVmyFft9EUp7BYv3Oej8PUn7FYsyGei2Bdm1JQmxBei8LVl8JejwDYtzJfk8JSk7FXk2AWqwMXm6MYs4KTkuObvwOem9Jam7HVsuNeo0Jal8LRg5DQj6EVkuMam9AUm7Jer2HSnxNQjuJShwKcn6CUl1CRkuKetwGSpxCRq0EclvCQi9LVmuJfq3KWm6EZs8DYv3Nek2JZpxMYjvKSk5PdqzJQh2CWg7CalvDWhyLQt8OVkvDenzCZuxETg6Kbq9MStzOVmyHZm5CUo5BWpuGbgwBVjuDcuuPYgzHdk5IQt3AVmyJYl6FUn6LVguKTo2DRg9NXguNbk2DYi6HTt5Gdl8KUowMUm9PfoxGShuMciwARi9AXm5BUgzLbruGQouCbtwEfm9Cfk2PakwOcsvNUl9BXk6GSi0FSu9Daq6PRq4MQg0Ico9OcrwNVr8BYjxBQv6JUuxNTh6NRs2Lci6Ibs7JTq0MTv3Nak8EQk9Ofl1JRouBUt3JdtyAcuvFZr7CYuvAVuwLUs7FfjwLcouIYn3Jet3JXj2BSlxMWn1KQt7Een5Adl7Cdn9Aas7JWg2JSt5Dav1OdhvBZo7OXr4NXjvEWu2LYhyPQrxCan0AUl1EesxPSpvCXn2Paq6KXt5Afn6LRt5PYh7ITuxGXo1Gcs5JdoyNXryKQi5Odt8ITruGRk5LcnzCXgvKem8AXt9Hbq5EaiyLXs6LYs4JWm1EcjuJVm3FSs8Ieg5Jfk3Ndn9CTl9NZsuAQu6OdrzFet1OXoyCYg0HSkyOTt5BYg9FRi0LSg0GVi2FVjwMXp5MVp3LZuwOcr8IQl3LRp0HTl3BXvzESixIVo0NXsvMei9LZixEbv8HXmzKXj4AYg9FRu7GZh8GbvuGQouMRl4LcpwHdi8FYk1Eeq1KTizISp9AWh9HTm7JRl2JXt2FRrwIYvuBQv3CVqvIXlwCfs6FVu2Eal7EXmyCfn4KQq1LZi9CXm0GYm3Mdm7FbgwOWp0Lak3Haj9KTkyJap3LYj6NQg0Kfk7Hcv7Hdm8FWnuGauwBXquOZn8Gcm4Per2Pcl7IWhvMbt4ObkxIQr9LRj9DZl8AfpzFer2JRk5ITlwJdp4IZoxNfpwDfh5GSo0Afh0MQuvEbl6NVovLRiuJQt4Adh1IdpuAUr8DXq8HegxMbn7KYoxGRt8MTj7DQivBYlvMXjyLVvvHRkyIam7Kbm9KYj1EcqyNbrwJVl3JRv8Mbs5DUo7EQqxIbi8Bfm6MciuIYn5FXp5BYg1OXr0PYm0KUn6KbjvIar3AVg7AfpzKSswCbluBSg5Feq4Pdn3PcmzCWm0Ffl4AXt0Bco0Ofj6Fft9CXi2GWm1GdjzORr9Bdu7GZq0Kcg4KfovFXt1GZt5CVp7CVvwOfl9ITu0Icu0MTvwIYu6PWvvNVowPYgwJZiwOXi8AWpvLTrxMWq8EThwLWh3CVl9Oct9Adt8Nfs9Kfj4GTq0LXv7Pdh0IUhuKSl7Det0GWnyLaq6CQkyCQuxDeh4OYn0Hes4KYh4Cfr9BXl1Kbr9Fck1ATh8KXlwMYsuDQg8OZuzASm1ITgyFZj2BZvyJXjyEes7Gbt4GWp7Afo7Jeo4JcluOTgxFcl8NZm3DTkyNcp0HSq8EfqwGSt9Lcp9CWqwNfq6OQuuPRu2DWouMVmyGei3MVt1MYlzAVk7JSo7LRh6JUn8JVn3GVhwAXvwDTnwPSk0KVv1Pcj3NXh4HdqvPdm5MUoyHej7IcgyMSsyLRpzIegyEVh1HRs0Bbp1CRu3Lcm3KStzKXixPcj7KbnvITp7BYg9EdjxLbg2FVhuJQg4EZk7OTjwDel7EStvPTk5OYmxPYuxEbs9Bfs3BeuvNQo1DesxBas1GZjuGbq9OTn6Laq5Ict3MTn2IVryJer6HTi9EdgxEZq4JYmyIbq6LfmzNeq8LYn3KZj2Ecn1FarvBanxLTt6KVjuFSm8Hbh5BZlwMag5PWuzFVovJZo5CZrzBQq9CTrxPTs1DUp1Feg7LbjxDZkvNbtvOQq8Hco5MZkvFerxDbk5HUmxHYhxHbtzCclzNWg0CVlzPeg1FUo6DVu5OauuAQizEVv1LXl3NblyLdo9Ifk1MZhxCZl3Kfu8Bft9DZgzHQs1Kdh6Jbp3Jdj5MXk9LdkwHamxAVgyDQp9GSszGXi1KSq1Mdv1DWryFRmvPSrzAQmvCeh0IYu1DenyBfpzPVv1Gfg8BVmzCXl3KdiuLSr4Adn4Ldq0AanvJcm8Fel1Iau1IaswLbu1EUq0CTmzObvzAYrvMQo5CUh1PTl2NdpvJVgwCfn4ATm6FZn2HZu1EeqzNQv2EZs1Edu3Kfo1AQm3AVi4FUt6CRlwPTl2HSquLRg5Mbj0LWv3JYv9OfnxPVizHZl2LVs4AYgxHSjuIUgwDXrvDah2EUg2Dcq7FRn5NdqyAQixOcquOYgxMUmxCXk8JXi4CSlwPfk6Kbh2HYm9PSn9Fbm9LWp3DRuvPfs0LYr8Jfp2HVsxEas5Aao9PZnzPdo6Pdk0IYh4DRqyJSp3Gfo7IZi8JQi2Fdu6NZk0MZm7FTu8JTg1OXjwLWi3Has4JZn2LehwBTnyOas4DcgvGRryKRruBelwPZl3Pdk9EbovPYl8BXj7FRp6MXu8CZrvATh0BWj0JVs8FcqzIQjxBZpvGRmvKZn4JQuwAeoxCYq6EQr1GVmwOQjuDQguFXozFZp2BRnwJTtuEXiuLZsxCZt7Ndk3DSquJZnuDdm3BTo6Jer6KZrzKRp9Kev8CbsuPcm6BalxHSp0PSi7Abu6Cbn0FTs2Bbo9NWm5Acv3IXsxGWm2KQk2DRk8FSu1Adp8NSi9LQq3MbrzHQjuIVt1BTl5LTi8JSkzNWm6HTjxJQryFTs6BSj8KQj8LUs3ESruFSo5OTq7KXpzHcl5Bau5GVs0AYrxPVk6IVo7EZt5PYs5LWvyDTvzKekwEZmyJSr4MSnuOXu5ERkuKen4BZo8AQv2MZp1Dan5OVq7OQt9HWl9FTm2BflwJUuyOfp3CUl4ESt5Jcj1Hfi8Cak4FUv3MQlvEZj8AXuwEXswPYl3Heu1ASg6OdtuEWs3Ccn4HZs1Adq8Ofg7PSn8HUg4GdmwJYv4Len7Gfv1OQv4NUg0MTl7DRl9GYu1KUqwEfu4EZh7PWswAek0Cdr5IRt4MRtxFXr2JZr4DXt6HSgyHes7Iau9KdvvIXr5CfvvPYjyCZjwPfn7OSvxGbr9GZn6Mcp9DSi6GbluATkzCSn0Ods7HTl0MUi3OYsvBZk9Gbh5DepxLak0MerxMfowHYjvEeivBcszLZq6Nfq5OXn1Ham9IXqvDbhyMcqyJeq6IZnwLUj2IVpwFZmzCav6Net0IXm2Bdg6Fbj2KRj3HcguKWjzHXpvNWm7GXk3HSp8Mdl4JSvzPSu3ARq8BTk7NdowOXs3DYh0MSpuIZk1BTuvLZi7EfmwFUhxGfhvJVu7MYnvGcvzKan6GXvwHft3Paq6HYo9MQovJUlxAbs1IViwDVgvJekzGdnuBSp5Aeu3DYt6AUn2NTv6LTkxEdj1LSr9Kbv7GUv8MUi8DVr0Iah6BXk2Dar6Jdk3Bbt5CTj2DctzBXsvDfrwIbn0EagwOcr1LUouGWg5GZuyNYj1LYg8Lar3Peo7EZk5OYkzDcn5NYk8HRl1JUj0LQm4IYnyNYlvBRvyCQn0AXpxGRhxHZpzIRvwFVv0HWg7DUkyDdr4Mcu3GWu1Ecu3CYn5Gfo0BSk9Lbq5Jdo9FUm3Ebq5Bai2IVg0Fcl1FYl0Beh0MZquDZsvLTk8BerwPct3Cbn4Deh3Ffr8Oan4Efh8PYm3BSt9FfpxMVsvJXj7DSk1JXquDZs8IWj8OTk1BTr2Peo9AeovEfjvAbh6JUvuPVg4OZjyDbq3Ibt7HfvuCSn8BatuLej4AZtwAYiwFamxPck1BSpxOUq6AXg9Fdu7Ndg3EUsyEWgzHfqxPUqvORv0GZu8JXj2Ccg6HUt9Aaq4EQquPai5Gdm6LTt3LTk4Aah4DVj2DWv0MalxLTr8PTk0MXm3KUgvKfovFZn8Lbn8Fao1KXq8CbovITizFSouPbvyIal8FZv1BZkyFUr9OVn5KRguAQgwCej1BVs1BWs1EUlvASqwARr4LWsyJel4GXgyKesuCZp3IajuMSs6MQkzLcl2Beo0IUhvHUu0NTt8EalvOWjzMYpwMZg9AUpwAZt7GZs9LZg0DcsvFXtzLQj1AbhwJTj0Pdg2Mfi6Ifk4HRgvLZs4JZgxHSo7BWrwBYo8Edj2KVvzCXg6BUjzHeq6Bbv8MUn9MbqyHfr0IVi3IfizFbsuCRs4NTkwIcn9HVm7BfhzNVpvGTqwObtuBYkzFRiwEQi8NSmyBUjwOau4Edt8AVh1CejvBei7MekxMSivPUk8ESizEfu9Jbg0GQh7HXk6MTtvFagzCbgwGSo2MdiuCYm2BWgzPei9PXruHbq1JSm7Fbk1CQq3IZg2IVm2PfhyITo6CRo9AWj2FQm4Hco4MSrwPSuvIXk9PZhyMbm2Kdp0DQg5Gdv0NYi6BVkyCVizJVhvAVg2Iei0CZi2BTo9FTlwIcuzOQr2Fej2FTnyEakuKWgyBWm8JcouEWm4IamwMfmxHZu8FXp3GQn1FXvuGYt8EYouFYu3FWp9KQrxCRi4Nfj2Ibr8BVjxIVk9EXm2DVu7Hem8Heh2EQhuIYlzMapyLcnxBal2CTk9ERtwEau6KcmzOTvvAfjxCWiyOVu3OYo2DXr0BdrvDekxOclwAdp9EZsxIXj3NQgvJZh4DTnxGft8NXl5NbpuOagzMbs9NZq6BUn5OSm0NSp9EZk0MZn4BSi9Mat5LWs4BZmxOZq5BckxFajyFbnxKRg8Pbs2HRvwGZn9PTlvNUpvNboyETnyDWlvOStuNWp0OZoxPdhwNfs9AVl9Gcq0MdlxIdp5EWq1CXm1CYm1GTkzNVvzPYv0Neh2NWh7HSq2Meo6Dfl8NXq7Icj4KRm9AcjyFZj1NYt3HQg1Idl2IajzLZt3AYjuLervOVs0KfqyKcu3CdmyNbs2AdhuHUi6JenvDVswBek2MYj0Ecj7PVn3HWh2GXmzLVp4MSm3IemvIVn1Per8Act0CbiuPanvBclvDSlzARs8FRizDciyAfr8EQg0MQhwHeg1MXm2BVjuIZp8PfouEbp8Cdq4KUn6Bel1JYl4Gdu4LQn8DSj9PTg6GRouBTs3EYn0CWm4ATp0PVj9AXj6Ecs2ITqvKSj8FeuxDdj7Mci5IepyIXqwOdvwHRk0Peg7BQk7HZv5OUg3HYt9ISv4Obl0EQk1BYk4Kei4AQizOduzAWs1BUuwOVhxBZjwFYp0EVguJYhzHbvuLXg9IdpuFSp6CWv4IehwPfi7JVl8ETj2Cco7ASkvBbjvAfv8GQs0Kes3Mbt9GSg4Ddm5Gdo3PehuOSvuFSl7JQuyBft3GYovBQu9NThzATs1DZj4CYu2Fbp5DVi2NZq4NbmyLSpxKatwAfp6DSnwHYnyIQm8FTm1JfjuHbm2CdnwPbk0BTquLSs4CYg6DfqxIatuLSs6KVgzCfs3IXoxFUs1ATrxDXv7MUl3IYm1EapwHbn2IVr7OYpxOeqvCfiuIRjxOWu0Kbv6FTruDQs5DWi2HYh4Mdt1Nas6OfpvFam7GdkzDZm5HVk6CQgzKRv8Bap4IWv8NcsxJatzCfm5KVv2Fel5PXq4BSl3FTu5LamyMYo4AXp7Ham9Bdq4BTk5BZh0JQj1EYlyLVsuDSt1IXu6FYq5JWvvJZk5KWh3NaizFSv6FZvzLVrwPXo4GVh2HTm4DZnvPUjyMYvwGes3JVg3Edq6Ech0MYs1JYgzCRk6NcvzMZmuJdiuGbqzGbh7FTo6KWh4KQmwCQu7KQp0GRs9OahwGfpyCbuvHXruNdg9IWnxHRm3FXvxPZq9CVnwPfr9CWnvCcoyAZu4Lev9HVj9LYluISswNQn1OWryPXp9JUtyBdg4BWm9Bco1MXq6EQl8OZpwCTlwHYr7Bfl2LZjzOUh3NXhuPYs5BWk7BSk2Oal9OZm4MXl6CQo3Heg8BTpuJcsxGYi3LQj0LXpxEaowHTpwIRu9Pfh6CYo3ATt3Aev0Lfp0HQo1BTn5KUozAfs6CWr2Jcm1DSq2IQh1OetyGcm7FZr3HYsuAaj6ATuzJVj5KRt6ASt6PRl4GeixGQvyMViwIVs5Pcq3JShzCQgvNQr6LSgvOdq8MRv4Bdg2NWjwLZg7BTl0ARpyATl1GWv6AUl7PYl4GRpzCbnxHRi6PWo8Eev3Mfh0Ccr8MarzGYg1FejuMUt0Fel3Pfh4CQtuFSg8Idm4IYt6LUm6Kcp7DXj0Jcl5ORtvIZhxFSquJekyBQjxORt3PQg9EaovAdmxOemuFei7FZuxEco0ERovOXixIQr5BQh6Edt8NTpxNao7HZvwEQs2MQi0KXn3GSouHei0EZtvAYj2GQvxPUm0IQl9OZu2LWs1PXp7GavwKYv7Fbm0Pft4DZr9Ocv5DQouDah2KWj4IUh6GcqzFTtyGciwMSmxMajyJck8NehzKWq8Aak7JWq0EUq3FZh5Keg4MXt6DTs3ARu7FTozEXiwBeq9DZk3BRm7FTkyBbj3KRjzEev3Lfr9GRixGas1Adv1KQi7KesvEfszDQj7BVqzMep4Oco9BVl6DVp8DeluDYjwNRp9JWp9MchvGYu4BQpzEZj0NdsuAbu3KTt7KZo8Jam7NcmvGTixPWt9LTiuPRt9Cem0IUsyOXt2LagyObszJSu6GXr7NXnuAdi3PbszOVtwKYl3ITi8FSr1FbsyOYlzGaryLbj4MdmwHRsyIVjvMbm9DVj2IYm0MTn1GYvvBTu7JSl7BUu4Nam5IagzBSi5JbgyNZryKfn8LSr9Iag2DWvzMUk6CXl8BehzHfuvBYt1OTn0NYkyLZrvKUq9BSn8FZnuBZt5CUj7KUo1GfqvOWg4AUg4ASq5AVu3NXh9JakvPZo2AevwBat5HSm7Oav3Eao7LXj9JXj1Cbv4BWp7PUq1Cfi1EflyMSiuBat4LSi0HVi7PXh4GRq9LYq8IRg2MUivAVl3LdqvLbpyHYlxOWi1Dfr3BXnlwEYmxFYn0GbkuEbmyFRnzGfk8EfmzFVn1GclwEalyGRn2HWkxETl4GUn1Gfk2EYmxFUn0Gak5ETk1EUm1DVkyEVjxGSiO0c2547b06bbdb8fda2c0c89f5e98de6720",
    "language": [{
        "language": "Chinese(Traditional)",
        "btnFirstPage": "第一頁",
        "btnNextPage": "下一頁",
        "btnLastPage": "最后一頁",
        "btnPrePage": "前一頁",
        "btnDownload": "下載",
        "btnPrint": "打印",
       // "btnSearch": "搜索",
        "btnClearSearch": "清除",
        "frmSearchPrompt": "清除",
        "btnBookMark": "目錄",
        "btnHelp": "幫助",
        "btnHome": "主頁",
        "btnFullScreen": "全屏",
        "btnDisableFullScreen": "普屏",
        "btnSoundOn": "打開聲音",
        "btnSoundOff": "關閉聲音",
        "btnShareEmail": "分享",
        "btnInstructions": "說明書",
        "btnSocialShare": "朋友分享",
        "btnZoomIn": "放大",
        "btnZoomOut": "縮小",
        "btnDragToMove": "拖動/移動",
        "btnAutoFlip": "自動翻頁",
        "btnStopAutoFlip": "停止翻頁",
        "btnGoToHome": "返回主頁",
        "frmHelpCaption": "幫助",
        "frmHelpTip1": "可以雙擊進行放大或縮小",
        "frmHelpTip2": "拖動頁面的個角可以進行翻頁",
        "frmPrintCaption": "打印窗口",
        "frmPrintBtnCaption": "打印",
        "frmPrintPrintAll": "打印所有頁面",
        "frmPrintPrintCurrentPage": "打印當前頁",
        "frmPrintPrintRange": "打印范圍：",
        "frmPrintExampleCaption": "例如：2,5,8-26",
        "frmPrintPreparePage": "正在準備頁：",
        "frmPrintPrintFailed": "打印失敗：",
        "pnlSearchInputInvalid": "（最少需要輸入2個字符）",
        "loginCaption": "登錄",
        "loginInvalidPassword": "你輸入的密碼不正確！",
        "loginPasswordLabel": "密碼：",
        "loginBtnLogin": "登錄",
        "loginBtnCancel": "取消",
        "btnThumb": "縮略圖",
        "lblPages": "頁數：",
        "lblPagesFound": "找到頁數：",
        "lblPageIndex": "頁",
        "btnAbout": "關于",
        "frnAboutCaption": "關于我們",
        "btnSinglePage": "單頁",
        "btnDoublePage": "雙頁",
        "btnSwicthLanguage": "切換語言",
        "tipChangeLanguage": "請在下面選擇一種語言",
        "btnMoreOptionsLeft": "更多選擇",
        "btnMoreOptionsRight": "更多選擇",
        "btnFit": "自動適應",
        "smallModeCaption": "點擊全屏",
        "btnAddAnnotation": "加注釋",
        "btnAnnotation": "注釋列表",
        "FlipPageEditor_SaveAndExit": "保存并退出",
        "FlipPageEditor_Exit": "退出",
        "DrawToolWindow_Redo": "重做",
        "DrawToolWindow_Undo": "撤銷",
        "DrawToolWindow_Clear": "清除",
        "DrawToolWindow_Brush": "筆刷",
        "DrawToolWindow_Width": "筆刷寬度",
        "DrawToolWindow_Alpha": "筆刷透明度",
        "DrawToolWindow_Color": "筆刷顔色",
        "DrawToolWindow_Eraser": "擦除",
        "DrawToolWindow_Rectangular": "矩形",
        "DrawToolWindow_Ellipse": "橢圓",
        "TStuff_BorderWidth": "邊框寬帶",
        "TStuff_BorderAlph": "邊框透明度",
        "TStuff_BorderColor": "字體顔色",
        "DrawToolWindow_TextNote": "文本附注",
        "AnnotMark": "書簽",
        "lastpagebtnHelp": "最后一頁",
        "firstpagebtnHelp": "第一頁",
        "homebtnHelp": "返回首頁",
        "aboubtnHelp": "關于",
        "screenbtnHelp": "在一個完整的窗口中打開該應用程序",
        "helpbtnHelp": "打開幫助窗口",
        "searchbtnHelp": "從書頁中搜索",
        "pagesbtnHelp": "預覽小冊子的縮略圖",
        "bookmarkbtnHelp": "打開目錄",
        "AnnotmarkbtnHelp": "打開書簽",
        "printbtnHelp": "打印小冊子",
        "soundbtnHelp": "開啟或關閉的聲音",
        "sharebtnHelp": "發送消息",
        "socialSharebtnHelp": "發送消息",
        "zoominbtnHelp": "放大",
        "downloadbtnHelp": "下載宣傳冊",
        "pagemodlebtnHelp": "單頁和雙頁",
        "languagebtnHelp": "切換語言",
        "annotationbtnHelp": "添加批注",
        "addbookmarkbtnHelp": "自定義書簽",
        "removebookmarkbtnHelp": "移除書簽",
        "updatebookmarkbtnHelp": "更新書簽",
        "btnShoppingCart": "購物車按鈕",
        "Help_ShoppingCartbtn": "購物車",
        "Help_btnNextPage": "下頁",
        "Help_btnPrePage": "上頁",
        "Help_btnAutoFlip": "自動翻頁",
        "Help_StopAutoFlip": "停止自動翻頁",
        "btnaddbookmark": "添加",
        "btndeletebookmark": "刪除",
        "btnupdatebookmark": "更新",
        "frmyourbookmarks": "你的書簽",
        "frmitems": "項目",
        "DownloadFullPublication": "整份出版物",
        "DownloadCurrentPage": "當前頁",
        "DownloadAttachedFiles": "附件",
        "lblLink": "分享鏈接",
        "btnCopy": "復制按鈕",
        "infCopyToClipboard": "瀏覽器不支持剪切板功能",
        "restorePage": "是否從上次的位置開始",
        "tmpl_Backgoundsoundon": "背景音樂開",
        "tmpl_Backgoundsoundoff": "背景音樂關",
        "tmpl_Flipsoundon": "翻頁聲開",
        "tmpl_Flipsoundoff": "翻頁聲關",
        "Help_PageIndex": "當前頁碼",
        "tmpl_PrintPageRanges": "頁范圍",
        "tmpl_PrintPreview": "預覽",
        "btnSelection": "選擇文字",
        "loginNameLabel": "您的名字:",
        "btnGotoPage": "跳至",
        "btnSettings": "設置",
        "soundSettingTitle": "聲音選項",
        "closeFlipSound": "翻頁聲開關",
        "closeBackgroundSound": "背景聲開關",
        "frmShareCaption": "分享",
        "frmShareLinkLabel": "鏈接:",
        "frmShareBtnCopy": "復制",
        "frmShareItemsGroupCaption": "朋友分享",
        "frmPanelTitle": "分享",
        "frmShareQRcode": "二维码",
        "TAnnoActionPropertyStuff_GotoPage": "轉到頁",
        "btnPageBack": "后退",
        "btnPageForward": "前進",
        "SelectTextCopy": "文本復制",
        "selectCopyButton": "復制",
        "TStuffCart_TypeCart": "購物車",
        "TStuffCart_DetailedQuantity": "數量",
        "TStuffCart_DetailedPrice": "價格",
        "ShappingCart_Close": "關閉",
        "ShappingCart_CheckOut": "付款",
        "ShappingCart_Item": "項目",
        "ShappingCart_Total": "總計",
        "ShappingCart_AddCart": "添加到購物車",
        "ShappingCart_InStock": "有貨",
        "TStuffCart_DetailedCost": "運費",
        "TStuffCart_DetailedTime": "交貨時間",
        "TStuffCart_DetailedDay": "天數(s)",
        "ShappingCart_NotStock": "無貨",
        "btnCrop": "截圖",
        "btnDragButton": "拖動",
        "btnFlipBook": "翻頁書",
        "btnSlideMode": "水平滑動翻頁",
        "btnSinglePageMode": "單頁模式",
        "btnVertical": "上下翻頁瀏覽",
        "btnHotizontal": "左右翻頁瀏覽",
        "btnClose": "關閉",
        "btnBookStatus": "視圖",
        "checkBoxInsert": "加入當前網頁",
        "lblLast": "這是最後一頁。",
        "lblFirst": "這是第一頁。",
        "lblFullscreen": "點擊查看全屏",
        "lblName": "名稱",
        "lblPassword": "密碼",
        "lblLogin": "登入",
        "lblCancel": "取消",
        "lblNoName": "用戶名稱不能為空。",
        "lblNoPassword": "密碼不能為空。",
        "lblNoCorrectLogin": "請輸入正確的用戶名和密碼。",
        "lblNoCorrectPass": "請輸入正確的密碼。",
        "btnVideo": "視頻畫廊",
        "btnSlideShow": "幻燈片放映",
        "btnPositionToMove": "滑鼠移動",
        "lblHelp1": "拖動頁面角查看",
        "lblHelp2": "按兩下放大，縮小",
        "lblCopy": "複製",
        "lblAddToPage": "添加到頁面",
        "lblPage": "頁",
        "lblTitle": "標題",
        "lblEdit": "編輯",
        "lblDelete": "删除",
        "lblRemoveAll": "删除所有",
        "tltCursor": "光標",
        "tltAddHighlight": "添加高亮",
        "tltAddTexts": "添加文字",
        "tltAddShapes": "添加形狀",
        "tltAddNotes": "添加注釋",
        "tltAddImageFile": "添加影像檔案",
        "tltAddSignature": "添加簽名",
        "tltAddLine": "添加直線",
        "tltAddArrow": "添加箭頭",
        "tltAddRect": "添加矩形",
        "tltAddEllipse": "添加橢圓",
        "lblDoubleClickToZoomIn": "雙擊進行放大。",
        "frmShareLabel": "分享",
        "frmShareInfo": "您可以輕鬆地分享本出版物中對社交網絡。只需點擊下面的相應按鈕。",
        "frminsertLabel": "插入到網站",
        "frminsertInfo": "使用下面的代碼本出版物中嵌入到你的網站。",
        "btnQRCode": "掃描二維碼",
        "btnRotateLeft": "左轉",
        "btnRotateRight": "右轉",
        "lblSelectMode": "請選擇顯示方式",
        "frmDownloadPreview": "預覽",
        "frmHowToUse": "使用說明",
        "lblHelpPage1": "頁角以及中間可手動翻頁",
        "lblHelpPage2": "雙擊或者用拉大手勢可以放大",
        "lblHelpPage3": "點擊logo 查看更多信息",
        "lblHelpPage4": "點擊工具欄按鈕進行搜索,分享等",
        "lblHelpPage5": "切換橫屏豎屏",
        "TTActionQuiz_PlayAgain": "重來一次",
        "TTActionQuiz_Ration": "你的評分是",
        "frmTelephone": "聯繫電話",
        "btnDialing": "呼叫",
        "lblSelectMessage": "請在文本框中復製文本內容。",
        "btnSelectText": "選擇文字",
        "btnNote": "筆記",
        "btnPhoneNumber": "聯繫電話",
        "btnWeCharShare": "微信分享",
        "btnMagnifierIn": "Magnifying Glass",
        "btnMagnifierOut": "Magnifier Reduction",
        "frmShareSmallProgram": "smallProgram",
        "btnMagnifier": "Magnifier",
        "frmPrintPrintLimitFailed": "Sorry, you can't print the pages.",
        "infNotSupportHtml5": "您的瀏覽器不支持HTML5。",
        "btnReport": "举报",
        "btnDoubleSinglePage": "Page switch",
        "frmBookMark": "書籤",
        "btnFullscreen": "全屏",
        "btnExitFullscreen": "退出全屏",
        "btnMore": "更多",
        "frmPrintall": "打印所有頁面",
        "frmPrintcurrent": "打印當前頁面",
        "frmPrintRange": "打印頁面範圍",
        "frmPrintexample": "示例: 2,3,5-10",
        "frmPrintbtn": "打印",
        "frmaboutcaption": "聯繫",
        "frmaboutcontactinformation": "聯繫信息",
        "frmaboutADDRESS": "地址",
        "frmaboutEMAIL": "電子郵件",
        "frmaboutWEBSITE": "網站",
        "frmaboutMOBILE": "手機",
        "frmaboutAUTHOR": "作者",
        "frmaboutDESCRIPTION": "描述",
        //"frmSearch": "搜尋",
        "frmToc": "目錄",
        "btnTableOfContent": "目錄",
        "lblDescription": "標題",
        "frmLinkLabel": "鏈接",
        "frmQrcodeCaption": "用手機掃描底部的二維碼。",
        "btnLanguage": "切換語言",
        "msgConfigMissing": "配置文件丟失，無法打開書籍。",
        "lblSave": "保存",
        "frmSharePanelTitle": "分享",
        "btnDownloadPosterPrompt": "點擊下載海報",
        "infLongPressToSavePoster": "長按保存海報",
        "infLongPressToIndentify": "長按識別二維碼",
        "infScanCodeToView": "掃描程式碼讀取",
        "lblConfirm": "確認",
        "infDeleteNote": "您要刪除此註釋嗎？",
        "btnBack": "後退",
        "proFullScreenWarn": "當前的瀏覽器不支持全屏，請使用Chrome以獲得最佳效果。",
        "frmVideoListTitle": "影片清單",
        "frmVideoTitle": "視頻",
        "doublePageTitle": "旋轉手機開啟雙頁閱讀模式",
        "doublePageDescription": "如何設置橫屏？",
        "doublePageGotIt": "知道了",
        "doublePageAndroidSettingStep1": "1.手機允許自動旋轉",
        "doublePageAndroidSettingStep2": "2. 閱讀電子書的瀏覽器需設置允許橫屏<br>如：微信-我-設置-通用-開啟橫屏模式",
        "doublePageAndroidSettingStep3": "3.手機橫過來閱讀書籍",
        "doublePageIPhoneSettingStep1": "1.手機豎排方向鎖定關閉",
        "doublePageIPhoneSettingStep2": "2.手機橫過來閱讀書籍"
    }],
    "fliphtml_pages": [{
        "l": "files/page/3pigstory.jpg",
        "t": "files/page/3pigstory.jpg"
    }, {
        "l": "files/page/strawhouse.jpg",
        "t": "files/page/strawhouse.jpg"
    }, {
        "l": "files/page/woodhouse.jpg",
        "t": "files/page/woodhouse.jpg"
    }, {
        "l": "files/page/brickhouse.jpg",
        "t": "files/page/brickhouse.jpg"
    }, {
        "l": "files/page/wolf_strawhouse.jpg",
        "t": "files/page/wolf_strawhouse.jpg"
    }, {
        "l": "files/page/wolf_woodhouse.jpg",
        "t": "files/page/wolf_woodhouse.jpg"
    }, {
        "l": "files/page/wolf_brickhouse.jpg",
        "t": "files/page/wolf_brickhouse.jpg"
    }, {
        "l": "files/page/wolf_chimney.jpg",
        "t": "files/page/wolf_chimney.jpg"
    }, {
        "l": "files/page/wolf_hotwater.jpg",
        "t": "files/page/wolf_hotwater.jpg"
    }, {
        "l": "files/page/strawhouse.jpg",
        "t": "files/page/strawhouse.jpg"
    }, {
        "l": "files/page/woodhouse.jpg",
        "t": "files/page/woodhouse.jpg"
    }, {
        "l": "files/page/brickhouse.jpg",
        "t": "files/page/brickhouse.jpg"
    }, {
        "l": "files/page/wolf_strawhouse.jpg",
        "t": "files/page/wolf_strawhouse.jpg"
    }, {
        "l": "files/page/wolf_woodhouse.jpg",
        "t": "files/page/wolf_woodhouse.jpg"
    }, {
        "l": "files/page/wolf_brickhouse.jpg",
        "t": "files/page/wolf_brickhouse.jpg"
    }, {
        "l": "files/page/wolf_chimney.jpg",
        "t": "files/page/wolf_chimney.jpg"
    }, {
        "l": "files/page/wolf_hotwater.jpg",
        "t": "files/page/wolf_hotwater.jpg"
    }
],
    "ols": [{
        "caption": "首頁",
        "page": 1,
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "A-PAGE3TAB",
        "page": "3",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "B-PAGE5TAB",
        "page": "5",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "C-PAGE7TAB",
        "page": "7",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "D-PAGE10TAB",
        "page": "10",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "E-PAGE12TAB",
        "page": "12",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "F-PAGE14TAB",
        "page": "14",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "G-PAGE15TAB",
        "page": "15",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "G-PAGE15TAB",
        "page": "16",
        "url": "",
        "level": 1,
        "children": []
    }, {
        "caption": "G-PAGE15TAB",
        "page": "17",
        "url": "",
        "level": 1,
        "children": []
    }
],
    "bmtConfig": {
        "tabs": [{
            "caption": "CH1",
            "color": "#298009",
            "pageIndex": 2,
            "fontColor": "#ffffff"
        }, {
            "caption": "CH2",
            "color": "#ED2B96",
            "pageIndex": 4,
            "fontColor": "#ffffff"
        }, {
            "caption": "CH3",
            "color": "#4163DD",
            "pageIndex": 5,
            "fontColor": "#ffffff"
        }, {
            "caption": "CH4",
            "color": "#F4580A",
            "pageIndex": 7,
            "fontColor": "#ffffff"
        }, {
            "caption": "CH5",
            "color": "#a50e9a",
            "pageIndex": 9,
            "fontColor": "#ffffff"
        }, {
            "caption": "CH6",
            "color": "#c2a60d",
            "pageIndex": 12,
            "fontColor": "#ffffff"
        }, {
            "caption": "CH7",
            "color": "#a5bfcf",
            "pageIndex": 15,
            "fontColor": "#ffffff"
        }],
        "hasTexture": false,
        "onSideEdge": false
    },
    "staticAd": {
        "haveAd": false,
        "adPosition": 0,
        "adHeight": 60,
        "interval": 3000,
        "data": []
    },
    "videoList": [],
    "slideshow": [],
    "flipByAudio": {
        "audioType": 0,
        "audioFile": "",
        "showPlayer": false,
        "items": []
    },
    "phoneNumber": [],
    "userList": {},
    "search_pages": [{
        "index": 0
    }, {
        "index": 1
    }, {
        "index": 2
    }, {
        "index": 3
    }, {
        "index": 4
    }, {
        "index": 5
    }, {
        "index": 6
    }, {
        "index": 7
    }, {
        "index": 8
    }, {
        "index": 9
    }, {
        "index": 10
    }, {
        "index": 11
    }, {
        "index": 12
    }, {
        "index": 13
    }, {
        "index": 14
    }, {
        "index": 15
    }, {
        "index": 16
    },  {
        "index": 17
    }],
    "downloadconfig": {
        "pdf": {
            "isOriginPath": false,
            "url": "",
            "urlOnlink": ""
        },
        "isDownloadProject": false,
        "isDownloadAttach": false,
        "attachments": []
    },
    "loadingConfig": {
        "loadingBackground": "#f23232",
        "loadingBackgroundColorType": 1,
        "loadingMainColor": "#323232",
        "loadingCaptionColor": "#DDDDDD",
        "loadingCaption": "組合 1",
        "loadingCaptionFontSize": "20",
        "loadingPicture": "",
        "loadingPictureHeight": "150",
        "showLoadingGif": "Yes",
        "loadingVideo": "",
        "loadingDisplayTime": "0",
        "loadingType": 0,
        "loadingVideoObjectFit": "fill",
        "loadingBrandInfoUrl": "",
        "loadingBrandInfoVisible": false,
        "loadingVideoCover": "",
        "isCloseVideoButtonVisible": false,
        "alwaysDoublePageOnMobile": false
    }
}
if (typeof window.htmlConfig !== 'undefined' && window.htmlConfig.fliphtml_pages) {
  window.readerConfig = {
    pages: window.htmlConfig.fliphtml_pages,
    totalPageCount: window.htmlConfig.fliphtml_pages.length
  };
  console.log('window.readerConfig prepared by config.js. Pages:', window.readerConfig.totalPageCount);
}
